---

#
# Ensure user_id is defined
#
- hosts: all
  tasks:
    - name: Assert that user_id is defined when running as root
      assert:
        msg: 'user_id must be defined when running as root (missing --extra-vars "user_id=USER"?)'
        that:
          - user_id is defined
      when: ansible_facts['user_id'] == "root"

    - name: Register user_id
      set_fact:
        user_id: "{{ ansible_user_id }}"
      when: ansible_facts['user_id'] != "root"
  tags: always

#
# Create main user and aur_builder
#
- hosts: all
  tasks:
    - import_role:
        name: user
      when: ansible_facts['user_id'] == "root"

    - name: Get user home directory
      changed_when: false
      register: getent
      shell: "getent passwd {{ user_id }}  | awk -F: '{ print $6 }'"

    - name: Register user_id
      set_fact:
        user_home: "{{ getent.stdout }}"
  tags: always

#
# Install base roles
#

- hosts: all
  roles: [ base ]
  tags:
    - alsa-utils
    - bc
    - build-essential
    - curl
    - dnsutils
    - feh
    - java
    - light
    - llpdp
    - nfs-common
    - scrot
    - sshpass
    - tcpdump
    - tlp
    - tree
    - unzip
    - xdg-user-dirs
    
- hosts: all
  roles: [ brave ]
  tags:
    - brave
 
- hosts: all
  roles: [ dunst ]
  tags:
    - dunst

- hosts: all
  roles: [ fonts ]
  tags:
    - fonts
 
- hosts: all
  roles: [ kitty ]
  tags:
    - kitty

- hosts: all
  roles: [ luakit ]
  tags:
    - vim
 
- hosts: all
  roles: [ mpv ]
  tags:
    - mpv

- hosts: all
  roles: [ parsec ]
  tags:
    - parsec

- hosts: all
  roles: [ picom ]
  tags:
    - picom

- hosts: all
  roles: [ rclone ]
  tags:
    - rclone

- hosts: all
  roles: [ remmina ]
  tags:
    - remmina
 
- hosts: all
  roles: [ rofi ]
  tags:
    - rofi

- hosts: all
  roles: [ runelite ]
  tags:
    - runelite

- hosts: all
  roles: [ sowm ]
  tags:
    - sowm

- hosts: all
  roles: [ spotify ]
  tags:
    - spotify

- hosts: all
  roles: [ tmux ]
  tags:
    - tmux

- hosts: all
  roles: [ user ]
  tags:
    - user

- hosts: all
  roles: [ vim ]
  tags:
    - vim

- hosts: all
  roles: [ wireshark ]
  tags:
    - wireshark

- hosts: all
  roles: [ xorg ]
  tags:
    - xorg

- hosts: all
  roles: [ zsh ]
  tags:
    - zsh

