# Windows
initial_window_width  60c
initial_window_height 10c
remember_window_size  no
window_padding_width  10
# Font
font_family           FiraCode Nerd Font Mono
bold_font             auto
italic_font           auto
bold_italic_font      auto
# Colors
# Black
color0                #3f444a
color8                #5b6268
# Red
color1                #ff6c6b
color9                #ff6655
# Green
Color2                #98be65
color10               #99bb66
# Yellow
color3                #ecbe7b
color11               #ecbe5b
# Blue
color4                #51afef
color12               #2257a0
# Magenta
color5                #c678dd
color13               #a9a1e1
# Cyan
color6                #46d9ff
color14               #5699af
# White
color7                #bbc2cf
color15               #bfbfbf
# Fore-, background, and cursorcolor
foreground            #bbc2cf
background            #282c34
cursor                #e16a98
selection_foreground  #bfbfbf
selection_background  #21242b